org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true

jvm=25
minecraft_version=26.1.2
neoForm_version=26.1.2-1
# NeoForge Properties
neo_loader_version=2
neoforge_version=26.1.2.30-beta
# Fabric Properties
fabric_loader_version=0.18.4

# Mod Properties
mod_name=EqualLoot
mod_id=equal_loot
mod_version=1.1.0
description=Adds a configurable per player mob loot system
mod_author=flemmli97
license=MIT
maven_group=io.github.flemmli97
issue_tracker=https://github.com/Flemmli97/EqualLoot/issues
sources_url=https://github.com/Flemmli97/EqualLoot

# Dependencies
fabric_api_version=0.147.0+26.1.2

# Curse properties
curseforge_versions=26.1.2, Java 25
curseforge_page=https://www.curseforge.com/minecraft/mc-mods/equal-loot
curseforge_id=1445150
curseforge_dep_fabric=fabric-api
curseforge_dep_neoforge=
modrinth_versions=26.1.2
modrinth_page=https://modrinth.com/mod/equal-loot
modrinth_id=gycZJL9N
modrinth_dep_fabric=fabric-api
modrinth_dep_neoforge=

# Other
project_name=EqualLoot
full_changelog=https://github.com/Flemmli97/EqualLoot/blob/26.1/Changelog.md